cc_test(
    name = "test_solver",
    srcs = ["test_solver.cpp"],
    deps = [
        "//mcts",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "test_tree",
    srcs = ["test_tree.cpp"],
    deps = [
        "//games/tic_tac_toe",
        "//mcts",
        "@com_google_googletest//:gtest_main",
    ],
)
